select (select count(*) from t_range_pk_1m),
       (select count(*) from t_hash_pk_1m),
       (select count(*) from t_range_pk_500k),
       (select count(*) from t_hash_pk_500k),
       (select count(*) from t_range_pk_200k),
       (select count(*) from t_hash_pk_200k),
       (select count(*) from t_range_pk_100k),
       (select count(*) from t_hash_pk_100k),
       (select count(*) from t_range_pk_1k),
       (select count(*) from t_hash_pk_1k);