select (select count(*) from t_range_pk_100k),
       (select count(*) from t_hash_pk_100k),
       (select count(*) from t_range_pk_50k),
       (select count(*) from t_hash_pk_50k),
       (select count(*) from t_range_pk_20k),
       (select count(*) from t_hash_pk_20k),
       (select count(*) from t_range_pk_10k),
       (select count(*) from t_hash_pk_10k),
       (select count(*) from t_range_pk_1k),
       (select count(*) from t_hash_pk_1k);