SELECT (SELECT COUNT(*) FROM t_range_100k),
       (SELECT COUNT(*) FROM t_range_200k),
       (SELECT COUNT(*) FROM t_range_300k),
       (SELECT COUNT(*) FROM t_range_400k),
       (SELECT COUNT(*) FROM t_range_500k),
       (SELECT COUNT(*) FROM t_range_600k),
       (SELECT COUNT(*) FROM t_range_700k),
       (SELECT COUNT(*) FROM t_range_800k),
       (SELECT COUNT(*) FROM t_range_900k),
       (SELECT COUNT(*) FROM t_range_1m),
       (SELECT COUNT(*) FROM t_range_100k_1update),
       (SELECT COUNT(*) FROM t_range_100k_2update),
       (SELECT COUNT(*) FROM t_range_100k_3update),
       (SELECT COUNT(*) FROM t_range_100k_4update),
       (SELECT COUNT(*) FROM t_range_100k_1column),
       (SELECT COUNT(*) FROM t_range_100k_2column),
       (SELECT COUNT(*) FROM t_range_100k_3column),
       (SELECT COUNT(*) FROM t_range_100k_4column);