-- -- t100 indexes
-- SELECT yb_index_check('t100_simple_index_1'::regclass);
-- SELECT yb_index_check('t100_simple_index_2'::regclass);
-- SELECT yb_index_check('t100_include_index_1'::regclass);
-- SELECT yb_index_check('t100_bucketized_1'::regclass);
-- SELECT yb_index_check('t100_bucketized_2'::regclass);
-- SELECT yb_index_check('t100_bucketized_3'::regclass);
-- SELECT yb_index_check('t100_bucketized_4'::regclass);
-- SELECT yb_index_check('t100_bucketized_5'::regclass);
-- SELECT yb_index_check('t100_bucketized_6'::regclass);
-- SELECT yb_index_check('t100_complex_index_1'::regclass);
-- SELECT yb_index_check('t100_complex_index_2'::regclass);
-- SELECT yb_index_check('t100_complex_index_3'::regclass);
-- SELECT yb_index_check('t100_complex_index_4'::regclass);
-- SELECT yb_index_check('t100_complex_index_5'::regclass);

-- -- t1000 indexes
-- SELECT yb_index_check('t1000_bucketized_1'::regclass);
-- SELECT yb_index_check('t1000_bucketized_2'::regclass);

-- -- t10000 indexes
-- SELECT yb_index_check('t10000_simple_index_1'::regclass);
-- SELECT yb_index_check('t10000_simple_index_2'::regclass);
-- SELECT yb_index_check('t10000_include_index_1'::regclass);
-- SELECT yb_index_check('t10000_bucketized_1'::regclass);
-- SELECT yb_index_check('t10000_bucketized_4'::regclass);
-- SELECT yb_index_check('t10000_bucketized_partition_1'::regclass);
-- SELECT yb_index_check('t10000_bucketized_partition_2'::regclass);
-- SELECT yb_index_check('t10000_bucketized_partition_3'::regclass);
-- SELECT yb_index_check('t10000_bucketized_partition_4'::regclass);
-- SELECT yb_index_check('t10000_bucketized_partition_def'::regclass);

-- -- t100000 indexes
-- SELECT yb_index_check('t100000_simple_index_1'::regclass);
-- SELECT yb_index_check('t100000_simple_index_2'::regclass);
-- SELECT yb_index_check('t100000_simple_index_3'::regclass);
-- SELECT yb_index_check('t100000_simple_index_4'::regclass);
-- SELECT yb_index_check('t100000_simple_index_5'::regclass);
-- SELECT yb_index_check('t100000_simple_index_6'::regclass);
-- SELECT yb_index_check('t100000_bucketized_1'::regclass);
-- SELECT yb_index_check('t100000_bucketized_2'::regclass);
-- SELECT yb_index_check('t100000_bucketized_3'::regclass);

-- -- t100000w indexes
-- SELECT yb_index_check('t100000w_simple_index_1'::regclass);
-- SELECT yb_index_check('t100000w_simple_index_2'::regclass);
-- SELECT yb_index_check('t100000w_simple_index_3'::regclass);
-- SELECT yb_index_check('t100000w_simple_index_4'::regclass);
-- SELECT yb_index_check('t100000w_simple_index_5'::regclass);
-- SELECT yb_index_check('t100000w_simple_index_6'::regclass);
-- SELECT yb_index_check('t100000w_bucketized_1'::regclass);
-- SELECT yb_index_check('t100000w_bucketized_2'::regclass);
-- SELECT yb_index_check('t100000w_bucketized_3'::regclass);
-- SELECT yb_index_check('t100000w_bucketized_4'::regclass);
-- SELECT yb_index_check('t100000w_bucketized_5'::regclass);

-- -- t1000000m indexes
-- SELECT yb_index_check('t1000000m_simple_index_1'::regclass);
-- SELECT yb_index_check('t1000000m_simple_index_2_c4c2c3c1'::regclass);
-- SELECT yb_index_check('t1000000m_simple_index_3_c5'::regclass);
-- SELECT yb_index_check('t1000000m_simple_index_4_c6'::regclass);
-- SELECT yb_index_check('t1000000m_simple_index_5_c3c4c5'::regclass);
-- SELECT yb_index_check('t1000000m_simple_index_6_c5c4c3'::regclass);
-- SELECT yb_index_check('t1000000m_bucketized_1'::regclass);
-- SELECT yb_index_check('t1000000m_bucketized_2'::regclass);
-- SELECT yb_index_check('t1000000m_bucketized_3'::regclass);
-- SELECT yb_index_check('t1000000m_bucketized_4'::regclass);
-- SELECT yb_index_check('t1000000m_bucketized_5'::regclass);

-- -- table_simple indexes
-- SELECT yb_index_check('table_simple_index_1'::regclass);
-- SELECT yb_index_check('table_simple_index_2'::regclass);
-- SELECT yb_index_check('table_simple_index_3'::regclass);
-- SELECT yb_index_check('table_simple_index_4'::regclass);

-- -- table_bucketized indexes
-- SELECT yb_index_check('table_bucketized_only_index_1'::regclass);
-- SELECT yb_index_check('table_bucketized_only_index_2'::regclass);
-- SELECT yb_index_check('table_bucketized_only_index_3'::regclass);
-- SELECT yb_index_check('table_bucketized_only_index_4'::regclass);
