name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Compute version
        id: ver
        run: |
          # Use tag without leading 'v' if present
          ref="${GITHUB_REF##*/}"
          echo "ref=$ref" >> $GITHUB_OUTPUT
          ver=${ref#v}
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Build release artifacts
        run: |
          set -euo pipefail
          mkdir -p dist
          # Build list of include paths present in repo
          include=(LICENSE README.md requirements.txt config docker bin scripts sql src adoc)
          present=()
          for p in "${include[@]}"; do
            [ -e "$p" ] && present+=("$p")
          done
          # Source tarball excluding venv and dot dirs except .github
          tar --exclude-vcs \
              --exclude=venv \
              --exclude=.venv \
              --exclude=report \
              --exclude=.git \
              --exclude='**/__pycache__' \
              -czf dist/taqo-yb-${{ steps.ver.outputs.version }}.tar.gz \
              -C . \
              "${present[@]}"

          # Zip of SQL models only
          if [ -d sql ]; then (cd sql && zip -r ../dist/sql-models-${{ steps.ver.outputs.version }}.zip .); fi

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: taqo-yb ${{ steps.ver.outputs.version }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') }}
          files: |
            dist/taqo-yb-${{ steps.ver.outputs.version }}.tar.gz
            dist/sql-models-${{ steps.ver.outputs.version }}.zip
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
